### ISSUE TITLE
commad 'sudo schroot -c anki -- apt install -y anki locales mplayer fonts-vlgothic fonts-takao' does not work

### ISSUE THREAD

**Issue by helasp** [gnprice/anki-jessie#1]
hello, is there a way to fix this?
it gives me an error 
```
E: Failed to execute “apt”: No such file or directory
```

**Comment by nibble** [comment]
Just yesterday I created a new schroot following again these instructions (from a stretch + backports host) and it worked flawlessly. Ensure every previous step has been executed successfully, specially this:

`sudo debootstrap jessie /srv/anki/chroot http://deb.debian.org/debian/`

**Comment by helasp** [comment]
after doing
```
sudo debootstrap jessie /srv/anki/chroot http://deb.debian.org/debian/
```
i get a warning (?)
```
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
```
is this the reason why it fails for me?

**Comment by nibble** [comment]
You don't have the Debian archive keyring file. What is your OS and version? Install/update the debian-keyring package or try passing the option --no-check-gpg to debootstrap.

**Comment by helasp** [comment]
thank you for the tips. i tried the ```sudo debootstrap --no-check-gpg jessie /srv/anki/chroot http://deb.debian.org/debian/```
option and it still didn't work. i have raspbian stretch with desktop: 
Linux raspberrypi 4.14.71-v7+ 
#1145 SMP Fri Sep 21 15:38:35 BST 2018. 
i tried installing debian-archive-keyring (prompt told me that it selected raspbian-archive-keyring), also debian-keyring. these are all i have
[<img src="https://i.postimg.cc/kXBttSpb/keyring.jpg">]
so i tried running sudo debootstrap with the --keyring=[path_to_keyring] options but now it tells me error: release signed by an unkown key (key id ... )
so i tried getting the raspbian public key, same error.

**Comment by nibble** [comment]
I have tried in a Rasperry Pi with raspbian stretch. The keyring is just a warning and doesn't prevent the bootstrap execution, sorry for the noise.

Everything has worked perfectly fine on my end. My only suggestion is to be extra careful when writing each command and each path, because it should work by following the instructions.

**Comment by helasp** [comment]
Thanks for trying to help. I couldn't get it to work but i will close the issue since it seems to be my mistake somewhere.
